apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  generation: 5
  labels:
    app: oso-centos7-host-monitoring
    deploymentconfig: oso-centos7-host-monitoring
  name: oso-centos7-host-monitoring
spec:
  selector:
    matchLabels:
      app: oso-centos7-host-monitoring
      deploymentconfig: oso-centos7-host-monitoring
  template:
    metadata:
      annotations:
        openshift.io/container.oso-centos7-host-monitoring.image.entrypoint: '["/bin/sh","-c","/usr/local/bin/start.sh"]'
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: oso-centos7-host-monitoring
        deploymentconfig: oso-centos7-host-monitoring
    spec:
      containers:
      - env:
        - name: PYTHONHTTPSVERIFY
          value: "0"
        image: docker.io/openshifttools/oso-centos7-host-monitoring@sha256:294151b444eb45b82b352fe950daf4ff4fbced75519a57b14506700b76b05d88
        imagePullPolicy: Always
        name: oso-centos7-host-monitoring
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /container_setup
          name: monitoring-config
        - mountPath: /sys
          name: sys
        - mountPath: /sys/fs/selinux
          name: selinux
        - mountPath: /var/lib/docker
          name: docker
        - mountPath: /etc/openshift
          name: etc-openshift
        - mountPath: /var/run/docker.sock
          name: docker-sock
      dnsPolicy: ClusterFirst
      nodeSelector:
        host-monitoring: "true"
      restartPolicy: Always
      securityContext: {}
      serviceAccount: host-monitoring
      serviceAccountName: host-monitoring
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: monitoring-config
        name: monitoring-config
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /sys/fs/selinux
        name: selinux
      - hostPath:
          path: /var/lib/docker
        name: docker
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock
      - hostPath:
          path: /etc/origin
        name: etc-openshift
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberMisscheduled: 0
